/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0631003e-833b-427b-9ce5-d819db1e82f1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5lSwFe1nB",
    "aws_user_pools_web_client_id": "52kcq4sgb55c5nv0c7vp0g0jka",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://szj7dq5t3fenlapstm7zi4fx4m.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nklmtml6pfdx7kmsrrpw7rv7si",
    "aws_user_files_s3_bucket": "mybucket112645-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
